python run_deeplab.py^
 --backbone=drn_c42^
 --out-stride=8^
 --dataset=cauGiay^
 --workers=8^
 --loss-type=ce^
 --fbeta=0.5^
 --epochs=1^
 --batch-size=8^
 --test-batch-size=4^
 --weight-decay=1e-8^
 --gpu-ids=0^
 --lr=1e-4^
 --loss-weights 0.5 0.5^
 --dropout 0.3 0.5^
 --checkname=_caugiay_drn_c42^
 --data-root=data\